version: 1
runtime: custom
vm: true
api_version: 1
application: animated-spider-811

manual_scaling:
  instances: 1

handlers:

- url: /(.*\.(html|css|js))
  static_files: public/\1
  upload: public/(.*\.(html|css|js))

- url: /.*
  script: app.js
  login: required