version: 1.2
runtime: custom
vm: true
api_version: 1
application: node-app-test-813

manual_scaling:
  instances: 1

handlers:
- url: /stylesheets
  static_dir: stylesheets

- url: /.*
  script: guestbook.application